import 'class.dart';

List<Class> classes = [
  Class(
    course: 'NS103',
    day: 'Monday',
    timeStart: 9,
    timeEnd: 10,
    group: Group.A,
    venue: Venue.L102,
  ),
  Class(
    course: 'NS103',
    day: 'Monday',
    timeStart: 11,
    timeEnd: 12,
    group: Group.B,
    venue: Venue.L202,
  ),
  Class(
    course: 'NS104',
    day: 'Monday',
    timeStart: 9,
    timeEnd: 10,
    group: Group.B,
    venue: Venue.L202,
  ),
  Class(
    course: 'NS104',
    day: 'Monday',
    timeStart: 11,
    timeEnd: 12,
    group: Group.A,
    venue: Venue.L102,
  ),
  Class(
    course: 'ES103',
    day: 'Monday',
    timeStart: 10,
    timeEnd: 11,
    group: Group.A,
    venue: Venue.L102,
  ),
  Class(
    course: 'ES103',
    day: 'Monday',
    timeStart: 12,
    timeEnd: 1,
    group: Group.B,
    venue: Venue.L202,
  ),
  Class(
    course: 'HS102',
    day: 'Monday',
    timeStart: 10,
    timeEnd: 11,
    group: Group.A,
    venue: Venue.L102,
  ),
  Class(
    course: 'HS102',
    day: 'Monday',
    timeStart: 12,
    timeEnd: 1,
    group: Group.B,
    venue: Venue.L202,
  ),
];
