import 'course.dart';

List<Course> courses = [
  // ********************************** SEM I *****************************************
  Course(
    name: 'Mathematics - I',
    code: 'NS101',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Engineering Mechanics',
    code: 'NS102',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Effective Communication Skills',
    code: 'HS101',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 2,
  ),
  Course(
    name: 'Fundamentals of Electrical and Electronics Engineering',
    code: 'ES101',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 5,
  ),
  Course(
    name: 'Fundamentals of Computing',
    code: 'ES102',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),

  // **************************** SEM II **********************************

  Course(
    name: 'Mathematics - II',
    code: 'NS103',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Electrodynamics and Optics',
    code: 'NS104',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 5,
  ),
  Course(
    name: 'Culture and Human Values',
    code: 'HS102',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 2,
  ),
  Course(
    name: 'Engineering Graphics',
    code: 'DS101',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 3,
  ),
  Course(
    name: 'Data Structures and Algorithms',
    code: 'ES103',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),

  // *********************************** SEM III *********************************

  Course(
    name: 'Advance Engineering Mathematics',
    code: 'NS2025a',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Analytical Method in Engineering',
    code: 'NS205b',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Discrete Mathematics',
    code: 'NS205c',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Applied Probability and Statistics',
    code: 'NS205d',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Numerical Method',
    code: 'NS205e',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Optimization',
    code: 'NS205f',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Modern Physics',
    code: 'NS205g',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Material Science',
    code: 'NS205h',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Culture and Science - a comparision',
    code: 'NS205i',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Digital Electronics',
    code: 'ES204',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Manufacturing Process',
    code: 'MN201',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Electronics Devices and Circuits',
    code: 'EC201',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 5,
  ),
  Course(
    name: 'Kinematics and Dynamics of Machines',
    code: 'ME201',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 4,
  ),
  Course(
    name: 'DBMS',
    code: 'CS201',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 4,
  ),
  Course(
    name: 'Instrumentation and Measurement',
    code: 'EC202',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'ECE',
    credits: 2,
  ),
  Course(
    name: 'IT Workshop',
    code: 'ME202',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: true,
    branch: 'ME',
    credits: 2,
  ),
  Course(
    name: 'Oops with Java',
    code: 'CS202',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'CSE',
    credits: 2,
  ),

  // ******************************* SEM IV *************************************

  Course(
    name: 'Fundamental of Robotics',
    code: 'ES205',
    sem: Semester.even,
    instructors: ['VKG', 'Aprajita Ojha', 'PKP'],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Management Concepts and Techniques',
    code: 'MS201',
    sem: Semester.even,
    instructors: ['SPS'],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Network Analysis and Synthesis',
    code: 'EC203',
    sem: Semester.even,
    instructors: ['RP', 'PKP'],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'ECE',
    credits: 4,
  ),
  Course(
    name: 'Thermodynamics',
    code: 'ME203',
    sem: Semester.even,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'ME',
    credits: 4,
  ),
  Course(
    name: 'Computer Organisation and Architecture',
    code: 'CS203',
    sem: Semester.even,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'CSE',
    credits: 4,
  ),
  Course(
    name: 'Signals and Systems',
    code: 'EC204',
    sem: Semester.even,
    instructors: ['IAA'],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'ECE',
    credits: 4,
  ),
  Course(
    name: 'Solid Mechanics',
    code: 'ME204',
    sem: Semester.even,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'ME',
    credits: 4,
  ),
  Course(
    name: 'Design and Analysis of Algorithm',
    code: 'CS204',
    sem: Semester.even,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'CSE',
    credits: 4,
  ),
  Course(
    name: 'Microprocessor and Interfacing',
    code: 'EC205',
    sem: Semester.even,
    instructors: ['AK'],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'ECE',
    credits: 2,
  ),
  Course(
    name: 'Engineering Materials',
    code: 'ME205',
    sem: Semester.even,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'ME',
    credits: 2,
  ),
  Course(
    name: 'Data Communication',
    code: 'CS205',
    sem: Semester.even,
    instructors: [],
    year: 'Second',
    group: false,
    lab: false,
    branch: 'CSE',
    credits: 4,
  ),
  Course(
    name: 'Microprocessor + Electronics',
    code: 'EC206L',
    sem: Semester.even,
    instructors: ['AK'],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 2,
  ),
  Course(
    name: 'Thermodynamics + Solid Mechanics',
    code: 'ME206L',
    sem: Semester.even,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 2,
  ),
  Course(
    name: 'Lab Based Project I',
    code: 'CS206L',
    sem: Semester.even,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 4,
  ),

  // ******************************** SEM V ************************************

  Course(
    name: 'Egineering Design',
    code: 'DS302',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Fundamental of Electromagnetic Theory',
    code: 'EC307',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 4,
  ),
  Course(
    name: 'Manufacturing Technology',
    code: 'ME307',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 4,
  ),
  Course(
    name: 'Computer Network',
    code: 'CS307',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 4,
  ),
  Course(
    name: 'Control Systems',
    code: 'EC308',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 4,
  ),
  Course(
    name: 'Fluid Mechanics',
    code: 'ME308',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 4,
  ),
  Course(
    name: 'Operating System',
    code: 'CS308',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 4,
  ),
  Course(
    name: 'Principle of Communication',
    code: 'EC309',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 4,
  ),
  Course(
    name: 'Design of Mechanical Components',
    code: 'ME309',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 4,
  ),
  Course(
    name: 'Language Theory',
    code: 'CS309',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 4,
  ),
  Course(
    name: 'Computer Networks',
    code: 'EC310a',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 2,
  ),
  Course(
    name: 'Digital System Design',
    code: 'EC310b',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 2,
  ),
  Course(
    name: 'Steam Turbine',
    code: 'ME310a',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 2,
  ),
  Course(
    name: 'Steam Generators',
    code: 'ME310b',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 2,
  ),
  Course(
    name: 'Gas Dynamics',
    code: 'ME310c',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 2,
  ),
  Course(
    name: 'Soft Computing',
    code: 'CS310a',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 2,
  ),
  Course(
    name: 'Parallel Computing',
    code: 'CS310b',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 2,
  ),
  Course(
    name: 'Coding Theory',
    code: 'CS310c',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 2,
  ),
  Course(
    name: 'Control Systems + Communication',
    code: 'EC311L',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 2,
  ),
  Course(
    name: 'FM&ST',
    code: 'ME311L',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 2,
  ),
  Course(
    name: 'Lab based Poject 2',
    code: 'CS311L',
    sem: Semester.odd,
    instructors: [],
    year: 'Third',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 2,
  ),

  // ********************************* SEM VI **********************************
];
