import 'course.dart';

List<Course> courses = [
  // ********************************** SEM I *****************************************
  Course(
    name: 'Mathematics - I',
    code: 'NS101',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Engineering Mechanics',
    code: 'NS102',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Effective Communication Skills',
    code: 'HS101',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 2,
  ),
  Course(
    name: 'Fundamentals of Electrical and Electronics Engineering',
    code: 'ES101',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 5,
  ),
  Course(
    name: 'Fundamentals of Computing',
    code: 'ES102',
    sem: Semester.odd,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),

  // **************************** SEM II **********************************

  Course(
    name: 'Mathematics - II',
    code: 'NS103',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Electrodynamics and Optics',
    code: 'NS104',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 5,
  ),
  Course(
    name: 'Culture and Human Values',
    code: 'HS102',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 2,
  ),
  Course(
    name: 'Engineering Graphics',
    code: 'DS101',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 3,
  ),
  Course(
    name: 'Data Structures and Algorithms',
    code: 'ES103',
    sem: Semester.even,
    instructors: [],
    year: 'First',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),

  // *********************************** SEM III *********************************

  Course(
    name: 'Advance Engineering Mathematics',
    code: 'NS2025a',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Analytical Method in Engineering',
    code: 'NS205b',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Discrete Mathematics',
    code: 'NS205c',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Applied Probability and Statistics',
    code: 'NS205d',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Numerical Method',
    code: 'NS205e',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Optimization',
    code: 'NS205f',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Modern Physics',
    code: 'NS205g',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Material Science',
    code: 'NS205h',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Culture and Science - a comparision',
    code: 'NS205i',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common + Optional',
    credits: 4,
  ),
  Course(
    name: 'Digital Electronics',
    code: 'ES204',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Manufacturing Process',
    code: 'MN201',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 4,
  ),
  Course(
    name: 'Electronics Devices and Circuits',
    code: 'EC201',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'ECE',
    credits: 5,
  ),
  Course(
    name: 'Kinematics and Dynamics of Machines',
    code: 'ME201',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 4,
  ),
  Course(
    name: 'DBMS',
    code: 'CS201',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'CSE',
    credits: 4,
  ),
  Course(
    name: 'Instrumentation and Measurement',
    code: 'EC202',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'ECE',
    credits: 2,
  ),
  Course(
    name: 'IT Workshop',
    code: 'ME202',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'ME',
    credits: 2,
  ),
  Course(
    name: 'Oops with Java',
    code: 'CS202',
    sem: Semester.odd,
    instructors: [],
    year: 'Second',
    group: true,
    lab: false,
    branch: 'CSE',
    credits: 2,
  ),

  // ******************************* SEM IV *************************************

  Course(
    name: 'Robotics',
    code: 'ES205',
    sem: Semester.even,
    instructors: ['VKG', 'Aprajita Ojha', 'PKP'],
    year: 'Second',
    group: true,
    lab: true,
    branch: 'Common',
    credits: 2,
  ),
];
