import 'package:iiitdmjcompanion/models/instructor/instructor.dart';

List<Instructor> instructors = [
  Instructor(
    name: 'Aparajita Ojha',
    phone: '+91-7612632044',
    email: 'aojha@iiitdmj.ac.in',
    designation: Designation.Professor,
    tilda: 'http://web.iiitdmj.ac.in/~aojha/',
    code: 'AO',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
      name: 'Atul Gupta',
      phone: '+91-761-2632139',
      email: 'atul@iiitdmj.ac.in',
      designation: Designation.Associate,
      tilda: 'https://sites.google.com/site/atulkg/',
      code: 'AG',
      building: Building.CC,
      dept: [Department.CSE],
      tags: [Tag.HODCSE]),
  Instructor(
    name: 'Pritee Khanna',
    phone: '+91 761 279 4222',
    email: 'pkhanna@iiitdmj.ac.in',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~pkhanna',
    code: 'PK',
    building: Building.CC,
    dept: [Department.CSE],
    tags: [Tag.ChairPlacement],
  ),
  Instructor(
    name: 'Sraban Kumar Mohanty',
    phone: '+91-761-2794224',
    email: 'sraban@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~sraban',
    code: 'SKM',
    building: Building.CC,
    dept: [Department.CSE],
    tags: [Tag.HeadTT],
  ),
  Instructor(
    name: 'Manish Kumar Bajpai',
    phone: '+91-761-2794227',
    email: 'mkbajpai@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~mkbakpai',
    code: 'MKB',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
    name: 'Vinod Kumar Jain',
    phone: '761-2794226',
    email: 'vkjain@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~vkjain',
    code: 'VKJ',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
    name: 'Ayan Seal',
    phone: '7612794229',
    email: 'ayan@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~ayan',
    code: 'AS',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
    name: 'Kusum Kumari Bharti',
    phone: '+91-7612794232',
    email: 'kusum@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~kusum',
    code: 'KKB',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
      name: 'Dinesh Kumar V',
      phone: '+91-761-2794463',
      email: 'dineshk@iiitdmj.ac.in',
      designation: Designation.Associate,
      tilda: 'http://web.iiitdmj.ac.in/~dineshk',
      code: 'DKV',
      dept: [Department.ECE],
      tags: [Tag.HODECE]),
  Instructor(
    name: 'Prabin K Padhy',
    phone: '+91-761-2794463',
    email: 'prabin16@iiitdmj.ac.in',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~prabin16',
    code: 'PKP',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'P.N. Kondekar',
    phone: '+91-761-2794460',
    email: 'pnkondekar@iiitdmj.ac.in',
    designation: Designation.Professor,
    tilda: 'http://web.iiitdmj.ac.in/~pnkondekar',
    code: 'PNK',
    dept: [Department.ECE],
    tags: [Tag.HeadCounselingService],
  ),
  Instructor(
    name: 'Ravi Panwar',
    email: 'rpanwar@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~rpanwar',
    code: 'RP',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Irshad Ahmad Ansari',
    phone: '+917612794067',
    email: 'irshad@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~irshad',
    code: 'IAA',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Trivesh Kumar',
    phone: '+917612794067',
    email: 'trivesh@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~trivesh',
    code: 'TK',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Atul Kumar',
    email: 'atul.kumar@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~atul.kumar',
    code: 'AK',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Dip Prakash Samajdar',
    phone: '+919477137992',
    email: 'dip.samajdar@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~dip.samajdar',
    code: 'DPS',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Biswajeet Mukherjee',
    phone: '+91-761-2794471',
    email: 'b.mukherjee@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~b.mukherjee',
    code: 'BM',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Varun Bajaj',
    phone: '+91-761-2794469',
    email: 'mbansal@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~mbansal',
    code: 'VB',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Manoj Singh Parihar',
    email: 'mparihar@iiitdmj.ac.in',
    phone: '+91-761-2794467',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~mparihar',
    code: 'MSP',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Sachin K. Jain',
    email: 'skjain@iiitdmj.ac.in',
    phone: '+91-761-2794468',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~skjain',
    code: 'SKJ',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Anil Kumar',
    email: 'anilk@iiitdmj.ac.in',
    phone: '+91-761-2794466',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~anilk',
    code: 'AK',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Jawar Singh',
    email: 'jawar@iiitdmj.ac.in',
    phone: '+91-761-2794464',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~jawar',
    code: 'JS',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Amarnath M.',
    email: 'amarnath@iiitdmj.ac.in',
    phone: '+91-761-2794417',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~amarnath',
    code: 'ACM',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Goutam Dutta',
    email: 'gd@iiitdmj.ac.in',
    phone: '+91-761-2794416',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~gd',
    code: 'GD',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'H. Chelladurai',
    email: 'chella@iiitdmj.ac.in',
    phone: '+91-761-2794418',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~chella',
    code: 'HC',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Harpreet Singh',
    email: 'hps.dme@iiitdmj.ac.in',
    phone: '+91-761-2794426',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~hps.dme',
    code: 'HS',
    dept: [Department.ME],
    tags: [Tag.CulturalCounsellor],
  ),
  Instructor(
    name: 'Himansu S Nanda',
    email: 'himansu@iiitdmj.ac.in',
    phone: '+917612794429',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~himansu',
    code: 'HSN',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Pavan Kankar',
    email: 'kankar@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~kankar',
    code: 'PK',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Prashant Kumar Jain',
    email: 'pkjain@iiitdmj.ac.in',
    phone: '+91-761-2794415',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~pkjain',
    code: 'PKJ',
    dept: [Department.ME],
    tags: [Tag.DeanStudents],
  ),
  Instructor(
    name: 'Mohd. Zahid Ansari',
    email: 'zahid@iiitdmj.ac.in',
    phone: '+91-761-2794422',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~zahid',
    code: 'MZA',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Puneet Tandon',
    email: 'ptandon@iiitdmj.ac.in',
    phone: '91-761-2794411',
    designation: Designation.Professor,
    tilda: 'http://web.iiitdmj.ac.in/~ptandon',
    code: 'PT',
    dept: [Department.ME, Department.Design],
    tags: [Tag.HODME],
  ),
  Instructor(
    name: 'Shivdayal Patel',
    email: 'shivdayal@iiitdmj.ac.in',
    phone: '07612794428',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~shivdayal',
    code: 'SP',
    dept: [Department.ME],
    tags: [Tag.TechnicalCounsellor],
  ),
  Instructor(
    name: 'Saurabh Pratap',
    email: 's.pratap@iiitdmj.ac.in',
    phone: '+91 7612794427',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~s.pratap',
    code: 'SPS',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Ponappa K',
    email: 'kponappa@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~kponappa',
    code: 'PK',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Sujoy Mukherjee',
    email: 'sujoy@iiitdmj.ac.in',
    phone: '+91-761-2794421',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~sujoy',
    code: 'SM',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Sunil Agrawal',
    email: 'sa@iiitdmj.ac.in',
    phone: '+91-761-2794414',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~sa',
    code: 'SA',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Tanuja Sheorey',
    email: 'tanush@iiitdmj.ac.in',
    phone: '+91-761-2794412',
    designation: Designation.Professor,
    tilda: 'http://web.iiitdmj.ac.in/~tanush',
    code: 'TS',
    dept: [Department.ME],
  ),
  Instructor(
      name: 'Vijay Kumar Gupta',
      email: 'vkgupta@iiitdmj.ac.in',
      phone: '+91-761-2794413',
      designation: Designation.Associate,
      tilda: 'http://web.iiitdmj.ac.in/~vkgupta',
      code: 'VKG',
      dept: [Department.ME],
      tags: [Tag.DeanAcad]),
  Instructor(
    name: 'Prabir Mukhopadhyay',
    email: 'prabir@iiitdmj.ac.in',
    phone: '+91-761-2794310',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~prabir',
    code: 'PM',
    dept: [Department.Design],
    tags: [Tag.HODDesign],
  ),
  Instructor(
    name: 'Sangeeta Pandit',
    email: 's.pandit@iiitdmj.ac.in',
    phone: '+91-761-2794314',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~s.pandit',
    code: 'SP',
    dept: [Department.Design],
  ),
  Instructor(
    name: 'Tripti Singh',
    email: 'ts@iiitdmj.ac.in',
    phone: '+91-761-2794313',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~ts',
    code: 'TS',
    dept: [Department.Design],
  ),
  Instructor(
    name: 'Amaresh Chandra Mishra',
    email: 'amresh@iiitdmj.ac.in',
    phone: '+91761-2794348',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~amresh',
    code: 'ACM',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Asish K. Kundu',
    email: 'asish.kundu@iiitdmj.ac.in',
    phone: '+91761-2794342',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~asish.kundu',
    code: 'AKK',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Mukesh Kumar Roy',
    email: 'mkroy@iiitdmj.ac.in',
    phone: '+91-761-2794350',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~mkroy',
    code: 'MKR',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Neeraj K. Jaiswal',
    email: 'neeraj@iiitdmj.ac.in',
    phone: '+91-761-2794352',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~neeraj',
    code: 'NKJ',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Yashpal Singh Katharria',
    email: 'yashpalk@iiitdmj.ac.in',
    phone: '+91 761 2794354',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~yashpalk',
    code: 'YSK',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Nihar Ranjan Jena',
    email: 'nrjena@iiitdmj.ac.in',
    phone: '+91-761-2794347',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~nrjena',
    code: 'NRJ',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Mamta Anand',
    email: 'manand@iiitdmj.ac.in',
    phone: '+91-761-2794268',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~manand',
    code: 'MA',
    dept: [Department.NS],
  ),
  Instructor(
    name: ' J. Al Muzzamil Fareen',
    email: 'jamfareen@iiitdmj.ac.in',
    phone: '+91-761-2794269',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~jamfareen',
    code: 'JAMF',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Bhupendra Gupta',
    email: 'bhupen@iiitdmj.ac.in',
    phone: '+91-761-2794345',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~bhupen',
    code: 'BG',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Deepmala',
    email: 'deepmala@iiitdmj.ac.in',
    phone: '91-761-2794353',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~deepmala',
    code: 'DM',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Lokendra Balyan',
    email: 'balyan@iiitdmj.ac.in',
    phone: '+91-761-2794346',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~balyan',
    code: 'LB',
    dept: [Department.NS],
  ),
  Instructor(
    name: '',
    email: '@iiitdmj.ac.in',
    phone: '',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~',
    code: '',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Manoj Kumar Panda',
    email: 'mkpanda@iiitdmj.ac.in',
    phone: '+91-761-2794351',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~mkpanda',
    code: 'MKP',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Nihar Kumar Mahato',
    email: 'nihar@iiitdmj.ac.in',
    phone: '+91-761-2794349',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~nihar',
    code: 'NKM',
    dept: [Department.NS],
  ),
  Instructor(
    name: 'Subir Lamba',
    email: 'subirs@iiitdmj.ac.in',
    phone: '+91-761-2794343',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~subirs',
    code: 'SL',
    dept: [Department.NS],
    tags: [Tag.HODNS],
  ),
];
