import 'package:iiitdmjcompanion/models/instructor/instructor.dart';

List<Instructor> instructors = [
  Instructor(
    name: 'Aparajita Ojha',
    phone: '+91-7612632044',
    email: 'aojha@iiitdmj.ac.in',
    designation: Designation.Professor,
    tilda: 'http://web.iiitdmj.ac.in/~aojha/',
    code: 'AO',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
    name: 'Atul Gupta',
    phone: '+91-761-2632139',
    email: 'atul@iiitdmj.ac.in',
    designation: Designation.Associate,
    tilda: 'https://sites.google.com/site/atulkg/',
    code: 'AG',
    building: Building.CC,
    dept: [Department.CSE],
    post: 'HOD-CSE',
  ),
  Instructor(
    name: 'Pritee Khanna',
    phone: '+91 761 279 4222',
    email: 'pkhanna@iiitdmj.ac.in',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~pkhanna',
    code: 'PK',
    building: Building.CC,
    dept: [Department.CSE],
    post: 'Chair-Placement',
  ),
  Instructor(
    name: 'Sraban Kumar Mohanty',
    phone: '+91-761-2794224',
    email: 'sraban@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~sraban',
    code: 'SKM',
    building: Building.CC,
    dept: [Department.CSE],
    post: 'Head-TT',
  ),
  Instructor(
    name: 'Manish Kumar Bajpai',
    phone: '+91-761-2794227',
    email: 'mkbajpai@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~mkbakpai',
    code: 'MKB',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
    name: 'Vinod Kumar Jain',
    phone: '761-2794226',
    email: 'vkjain@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~vkjain',
    code: 'VKJ',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
    name: 'Ayan Seal',
    phone: '7612794229',
    email: 'ayan@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~ayan',
    code: 'AS',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
    name: 'Kusum Kumari Bharti',
    phone: '+91-7612794232',
    email: 'kusum@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~kusum',
    code: 'KKB',
    building: Building.CC,
    dept: [Department.CSE],
  ),
  Instructor(
    name: 'Dinesh Kumar V',
    phone: '+91-761-2794463',
    email: 'dineshk@iiitdmj.ac.in',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~dineshk',
    code: 'DKV',
    dept: [Department.ECE],
    post: 'HOD-ECE',
  ),
  Instructor(
    name: 'Prabin K Padhy',
    phone: '+91-761-2794463',
    email: 'prabin16@iiitdmj.ac.in',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~prabin16',
    code: 'PKP',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'P.N. Kondekar',
    phone: '+91-761-2794460',
    email: 'pnkondekar@iiitdmj.ac.in',
    designation: Designation.Professor,
    tilda: 'http://web.iiitdmj.ac.in/~pnkondekar',
    code: 'PNK',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Ravi Panwar',
    email: 'rpanwar@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~rpanwar',
    code: 'RP',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Irshad Ahmad Ansari',
    phone: '+917612794067',
    email: 'irshad@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~irshad',
    code: 'IAA',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Trivesh Kumar',
    phone: '+917612794067',
    email: 'trivesh@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~trivesh',
    code: 'TK',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Atul Kumar',
    email: 'atul.kumar@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~atul.kumar',
    code: 'AK',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Dip Prakash Samajdar',
    phone: '+919477137992',
    email: 'dip.samajdar@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~dip.samajdar',
    code: 'DPS',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Biswajeet Mukherjee',
    phone: '+91-761-2794471',
    email: 'b.mukherjee@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~b.mukherjee',
    code: 'BM',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Varun Bajaj',
    phone: '+91-761-2794469',
    email: 'mbansal@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~mbansal',
    code: 'VB',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Manoj Singh Parihar',
    email: 'mparihar@iiitdmj.ac.in',
    phone: '+91-761-2794467',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~mparihar',
    code: 'MSP',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Sachin K. Jain',
    email: 'skjain@iiitdmj.ac.in',
    phone: '+91-761-2794468',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~skjain',
    code: 'SKJ',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Anil Kumar',
    email: 'anilk@iiitdmj.ac.in',
    phone: '+91-761-2794466',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~anilk',
    code: 'AK',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Jawar Singh',
    email: 'jawar@iiitdmj.ac.in',
    phone: '+91-761-2794464',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~jawar',
    code: 'JS',
    dept: [Department.ECE],
  ),
  Instructor(
    name: 'Amarnath M.',
    email: 'amarnath@iiitdmj.ac.in',
    phone: '+91-761-2794417',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~amarnath',
    code: 'ACM',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Goutam Dutta',
    email: 'gd@iiitdmj.ac.in',
    phone: '+91-761-2794416',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~gd',
    code: 'GD',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'H. Chelladurai',
    email: 'chella@iiitdmj.ac.in',
    phone: '+91-761-2794418',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~chella',
    code: 'HC',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Harpreet Singh',
    email: 'hps.dme@iiitdmj.ac.in',
    phone: '+91-761-2794426',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~hps.dme',
    code: 'HS',
    dept: [Department.ME],
    post: 'Cultural-Counsellor',
  ),
  Instructor(
    name: 'Himansu S Nanda',
    email: 'himansu@iiitdmj.ac.in',
    phone: '+917612794429',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~himansu',
    code: 'HSN',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Pavan Kankar',
    email: 'kankar@iiitdmj.ac.in',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~kankar',
    code: 'PK',
    dept: [Department.ME],
  ),
  Instructor(
      name: 'Prashant Kumar Jain',
      email: 'pkjain@iiitdmj.ac.in',
      phone: '+91-761-2632644, 125',
      designation: Designation.Associate,
      tilda: 'http://web.iiitdmj.ac.in/~pkjain',
      code: 'PKJ',
      dept: [Department.ME],
      post: 'Dean-Students'),
  Instructor(
    name: 'Mohd. Zahid Ansari',
    email: 'zahid@iiitdmj.ac.in',
    phone: '+91-761-2794422',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~zahid',
    code: 'MZA',
    dept: [Department.ME],
  ),
  Instructor(
      name: 'Puneet Tandon',
      email: 'ptandon@iiitdmj.ac.in',
      phone: '+91-761-2632924, 9-824',
      designation: Designation.Professor,
      tilda: 'http://web.iiitdmj.ac.in/~ptandon',
      code: 'PT',
      dept: [Department.ME, Department.Design],
      post: 'HOD-ME'),
  Instructor(
    name: 'Shivdayal Patel',
    email: 'shivdayal@iiitdmj.ac.in',
    phone: '+91 761-2794428',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~shivdayal',
    code: 'SP',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Saurabh Pratap',
    email: 's.pratap@iiitdmj.ac.in',
    phone: '+91 7612794427',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~s.pratap',
    code: 'SPS',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Sujoy Mukherjee',
    email: 'sujoy@iiitdmj.ac.in',
    phone: '+91-761-263664, 158',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~sujoy',
    code: 'SM',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Sunil Agrawal',
    email: 'sa@iiitdmj.ac.in',
    phone: '+91-761-2633955, 9-855',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~sa',
    code: 'SA',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Tanuja Sheorey',
    email: 'tanush@iiitdmj.ac.in',
    phone: '+91-761-2632657,9-657',
    designation: Designation.Professor,
    tilda: 'http://web.iiitdmj.ac.in/~tanush',
    code: 'TS',
    dept: [Department.ME],
  ),
  Instructor(
    name: 'Vijay Kumar Gupta',
    email: 'vkgupta@iiitdmj.ac.in',
    phone: '+91-761-2632696, 9-696',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~vkgupta',
    code: 'VKG',
    dept: [Department.ME],
    post: 'Dean-Academics',
  ),
  Instructor(
    name: 'Prabir Mukhopadhyay',
    email: 'prabir@iiitdmj.ac.in',
    phone: '+91-761-2794310',
    designation: Designation.Associate,
    tilda: 'http://web.iiitdmj.ac.in/~prabir',
    code: 'PM',
    dept: [Department.Design],
  ),
  Instructor(
    name: 'Sangeeta Pandit',
    email: 's.pandit@iiitdmj.ac.in',
    phone: '+91-761-2794314',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~s.pandit',
    code: 'SP',
    dept: [Department.Design],
  ),
  Instructor(
    name: 'Tripti Singh',
    email: 'ts@iiitdmj.ac.in',
    phone: '+91-761-2794313',
    designation: Designation.Assistant,
    tilda: 'http://web.iiitdmj.ac.in/~ts',
    code: 'TS',
    dept: [Department.Design],
  ),
];
